openapi: 3.0.0
info:
  title: Todo API
  description: シンプルなTodo管理API
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: 開発環境
tags:
  - name: task
    description: タスク関連API（PocoTechレクチャー）
  - name: Todo
    description: Todo管理に関する操作（AI自動生成コード）
  - name: opts
    description: 運用監視用API（AI自動生成コード）

paths:
  /tasks:
    post:
      summary: "タスク作成"
      description: "タスクを新規作成します"
      operationId: createTask
      tags:
        - task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskForm'
      responses:
        '201':
          description: "created"
          headers:
            location:
              description: "作成されたリソースのURI"
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDTO'
        '400':
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
  /tasks/{taskId}:
    get:
      tags:
        - task
      operationId: showTask
      parameters:
        - name: taskId
          in: path
          required: true
          description: "詳細を取得するタスクのID"
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDTO'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundError'

  /api/todos:
    get:
      summary: すべてのTodoを取得
      operationId: getTodos
      tags:
        - Todo
      responses:
        '200':
          description: Todoリストの取得に成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: 新しいTodoを作成
      operationId: createTodo
      tags:
        - Todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoRequest'
      responses:
        '201':
          description: Todoの作成に成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

  /api/todos/{id}:
    get:
      summary: 特定のTodoを取得
      operationId: getTodoById
      tags:
        - Todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Todoの取得に成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todoが見つかりません

    put:
      summary: Todoを更新
      operationId: updateTodo
      tags:
        - Todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoRequest'
      responses:
        '200':
          description: Todoの更新に成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

    delete:
      summary: Todoを削除
      operationId: deleteTodo
      tags:
        - Todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Todoの削除に成功

  /health:
    get:
      summary: サービスのヘルスチェック
      operationId: healthCheck
      tags:
        - opts
      responses:
        '200':
          description: サービスは正常に稼働中
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "UP"

components:
  schemas:
    TaskForm:
      type: object
      properties:
        title:
          type: string
          description: "作成されるタスクのタイトル"
      required:
        - title
    TaskDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "タスクID"
        title:
          type: string
          description: "タスクのタイトル"
      required:
        - id
        - title
    ResourceNotFoundError:
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイトル"
          default: "Resource Not Found"
        detail:
          type: string
          description: "エラーの詳細"
      required:
        - title
        - detail
    BadRequestError:
      description: "リクエストが不正"
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイトル"
          default: "Bad Request"
        detail:
          type: string
          description: "エラーの詳細"
          default: "リクエストが不正です。正しいリクエストでリトライしてください"
        invalid-params:
          type: array
          items:
            $ref: "#/components/schemas/InvalidParam"
      required:
        - title
        - detail
        - invalid-params
    InvalidParam:
      description: "不正なリクエストについての詳細"
      type: object
      properties:
        name:
          type: string
          description: "エラーが発生したフィールド名"
        reason:
          type: string
          description: "エラーの理由"
      required:
        - name
        - reason
    Todo:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "買い物に行く"
        description:
          type: string
          example: "牛乳とパンを買う"
        completed:
          type: boolean
          example: false
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - title
        - completed

    CreateTodoRequest:
      type: object
      properties:
        title:
          type: string
          example: "買い物に行く"
        description:
          type: string
          example: "牛乳とパンを買う"
        completed:
          type: boolean
          example: false
      required:
        - title
